"""Correcciones y ampliaciones del banco que no están en datos/banco.csv.

Todo lo de aquí lo añadió Claude al revisar el banco (2026-09-23) y conviene
revisarlo: niveles de las categorías cerradas, respuestas que faltaban y
formas de escribir (alias) con las que una respuesta correcta se daba por mala.

- NIVELES: reasigna niveles en categorías cuyo CSV los traía en orden
  alfabético o de lista. Formato {categoría: {nivel: "a|b|c"}, "resto": n}.
- NUEVAS: respuestas que faltaban. Una por línea: "nivel|Respuesta|alias;alias".
- ALIAS_CAT: formas alternativas por categoría {categoría: {"Respuesta": "alias;alias"}}.
"""

L = lambda s: [x.strip() for x in s.split("|") if x.strip()]

# ─────────────────────────── niveles reasignados ───────────────────────────
PAISES_NIVEL = {
 1: L("España|Francia|Alemania|Italia|Portugal|Reino Unido|Estados Unidos|México|Argentina|Brasil|China|Japón|Rusia|India|Canadá|Australia|Marruecos|Egipto"),
 2: L("Grecia|Países Bajos|Bélgica|Suiza|Austria|Irlanda|Suecia|Noruega|Dinamarca|Finlandia|Polonia|Turquía|Ucrania|Colombia|Chile|Perú|Venezuela|Cuba|Uruguay|Ecuador|Bolivia|Paraguay|Corea del Sur|Corea del Norte|Tailandia|Vietnam|Indonesia|Filipinas|Israel|Iran|Irak|Arabia Saudí|Emiratos Árabes Unidos|Catar|República de Sudáfrica|Nigeria|Argelia|Túnez|Nueva Zelanda|Croacia|Rumania|Hungría|República Checa|Islandia|Andorra|Pakistán|Afganistán|Siria|Costa Rica|Panamá|Guatemala|Honduras|República Dominicana|Senegal|Kenia|Mónaco|Palestina"),
 3: L("Nicaragua|El Salvador|Jamaica|Haiti|Bulgaria|Serbia|República Eslovaca|Eslovenia|Luxemburgo|Malta|Chipre|Albania|Etiopía|Ghana|Camerún|Costa de Marfil|Angola|Mozambique|Libia|Sudán|Somalia|Madagascar|Tanzania|Congo (Rep. Dem.)|Mali|Mauritania|Guinea Ecuatorial|Nepal|Bangladesh|Sri Lanka|Singapur|Malasia|Mongolia|Kazajistán|Georgia|Armenia|Bielorrusia|Lituania|Letonia|Estonia|Bosnia y Herzegovina|Montenegro|Macedonia|Moldavia|San Marino|Liechtenstein|Líbano|Jordania|Kuwait|Omán|Yemen|Camboya|Myanmar (Birmania)|Zimbabue|Ruanda|Uganda|Bahamas|Maldivas|Uzbekistán|Guinea|Congo|Namibia|Zambia|Botswana|Laos|Vaticano|Taiwán|Kosovo"),
 5: L("Tuvalu|Nauru|Palau|Kiribati|Islas Marshall|Micronesia|Vanuatu|Islas Salomón|Tonga|Samoa|Comoras|Santo Tomé y Príncipe|San Cristóbal y Nieves|San Vicente y Granadinas|Santa Lucía|Dominica|Grenada|Antigua y Barbuda|Yibuti|Eritrea|Lesotho|Suazilandia|Burundi|Bután|Brunei|Timor Oriental|Turkmenistán|Tayikistán|Kirguizistán"),
 "resto": 4,
}
NIVELES = {
 1: {1: L("Andalucía|Cataluña|Comunidad de Madrid|Comunitat Valenciana|Galicia|País Vasco"),
     2: L("Canarias|Illes Balears|Castilla y León|Castilla-La Mancha|Aragón|Principado de Asturias|Extremadura|Región de Murcia"),
     3: L("Cantabria|Comunidad Foral de Navarra|La Rioja"), 4: L("Ceuta"), 5: L("Melilla"), "resto": 3},
 2: {1: L("Madrid|Barcelona|Valencia|Sevilla|Málaga|Alicante|Zaragoza|Murcia|Granada|Cádiz|Asturias"),
     2: L("Córdoba|Toledo|Salamanca|Bizkaia|A Coruña|Pontevedra|Illes Balears|Navarra|Cantabria|Valladolid|Gipuzkoa|León|Burgos|Almería|Huelva|Jaén|Tarragona|Girona|Castellón|Badajoz|Cáceres|Segovia|Las Palmas|Santa Cruz de Tenerife|La Rioja"),
     3: L("Álava|Lleida|Huesca|Albacete|Ciudad Real|Lugo|Ourense"),
     4: L("Soria|Teruel|Cuenca|Guadalajara|Ávila"), 5: L("Palencia|Zamora"), "resto": 3},
 3: {1: L("Madrid|Barcelona|Valencia|Sevilla|Málaga|Zaragoza|Bilbao|Murcia|Granada|Alicante|Córdoba|Cádiz|Palma"),
     2: L("Toledo|Salamanca|Valladolid|Santander|Oviedo|A Coruña|Pamplona|Donostia-San Sebastián|Almería|Huelva|Jaén|León|Burgos|Tarragona|Girona|Las Palmas de Gran Canaria|Santa Cruz de Tenerife|Logroño|Badajoz|Cáceres|Segovia|Vitoria-Gasteiz|Pontevedra"),
     3: L("Castellón de la Plana|Lleida|Ourense|Lugo|Huesca|Albacete|Ciudad Real"),
     4: L("Cuenca|Guadalajara|Ávila|Soria|Teruel"), 5: L("Zamora|Palencia"), "resto": 3},
 5: {1: L("Real Madrid|FC Barcelona|Atlético de Madrid|Sevilla FC|Valencia CF|Athletic Club|Real Betis"),
     2: L("Real Sociedad|Villarreal CF|Celta|RCD Espanyol de Barcelona|CA Osasuna|Getafe CF|Rayo Vallecano|RC Deportivo de La Coruña|Málaga CF"),
     3: L("Deportivo Alavés|Levante UD|Elche CF|Racing Club de Santander"), "resto": 3},
 6: PAISES_NIVEL, 9: PAISES_NIVEL, 10: PAISES_NIVEL, 11: PAISES_NIVEL, 12: PAISES_NIVEL, 14: PAISES_NIVEL,
 7: {1: L("Madrid|Londres|Paris|Rome|Berlin|Lisbon|Washington D.C.|Moscow|Tokyo|Beijing|Buenos Aires|Mexico City|Brussels|Amsterdam|Athens"),
     2: L("Vienna|Dublin|Stockholm|Oslo|Copenhagen|Helsinki|Warsaw|Prague|Budapest|Bern|Ottawa|Canberra|Brasília|Lima|Santiago|Bogotá|Caracas|Havana|Montevideo|Quito|Cairo|Rabat|Ankara|Kiev|Seoul|Bangkok|New Delhi|Jerusalem|Tehran|Baghdad|Kabul|Andorra la Vella|Monaco|Luxembourg|Reykjavik|Panama City|Asunción|San José|Guatemala City|Santo Domingo|Wellington|Hanoi|Manila|Jakarta|Riyadh|Doha|Abu Dhabi|Damascus|Beirut|Tunis|Algiers|Dakar|Nairobi|Bucharest|Sofia|Belgrade|Zagreb|Islamabad"),
     3: L("Bratislava|Ljubljana|Tirana|Sarajevo|Skopje|Podgorica|Minsk|Vilnius|Riga|Tallinn|Chișinău|Valletta|Nicosia|Vaduz|City of San Marino|Tbilisi|Yerevan|Baku|Astana|Kathmandu|Dhaka|Kuala Lumpur|Singapore|Ulan Bator|Pyongyang|Phnom Penh|Amman|Kuwait City|Muscat|Sana'a|Addis Ababa|Pretoria|Luanda|Kinshasa|Khartoum|Tripoli|Managua|Tegucigalpa|San Salvador|Kingston|Port-au-Prince|Nassau|Sucre|Malabo|Accra|Abuja|Kampala|Harare|Maputo|Antananarivo|Tashkent|Malé|Vientiane|Mogadishu|Nouakchott|Bamako|Lusaka|Windhoek|Kigali|Yaoundé"),
     5: L("Ngerulmud|Palikir|Majuro|South Tarawa|Funafuti|Yaren|Honiara|Port Vila|Nuku'alofa|Apia|Moroni|São Tomé|Basseterre|Kingstown|Castries|Roseau|St. George's|Saint John's|Gitega|Sri Jayawardenepura Kotte|Naipyidó|Yamoussoukro|Porto-Novo|Thimphu|Bandar Seri Begawan|Dili|Ashgabat|Dushanbe|Bishkek|Mbabane|Maseru|Asmara|Djibouti"),
     "resto": 4},
 8: {1: L("Euro|Dólar estadounidense|Libra esterlina|Yen japonés|Peso mexicano|Peso argentino|Franco suizo|Rublo ruso|Yuan chino"),
     2: L("Dólar canadiense|Dólar australiano|Real brasileño|Rupia india|Lira turca|Peso colombiano|Peso chileno|Won surcoreano|Corona sueca|Corona noruega|Corona danesa|Dírham marroquí|Bolívar venezolano|Sol peruano|Zloty polaco|Dólar neozelandés|Cuban Peso|Peso uruguayo|Libra egipcia|Rand|Corona checa|Forinto húngaro|Riyal saudí|Dírham de los EAU|Nuevo séquel israelí|Baht tailandés"),
     3: L("Boliviano|Guaraní paraguayo|Quetzal|Lempira|Balboa|Costa Rican Colon|Dominican Peso|Rupia pakistaní|Dong vietnamita|Peso filipino|Ringit malasio|Dólar de Singapur|Rupia indonesia|Dinar argelino|Dinar tunecino|Dinar kuwaití|Riyal catarí|Rial iraní|Leu rumano|Lev búlgaro|Grivna ucraniana|Corona islandesa|Dinar jordano|Dinar iraquí|Naira nigeriana|Chelín keniano|Cedi ghanés|Taka bangladesí|Rupia nepalesa|Rupia de Sri Lanka|Tenge|Rial omaní|Dinar bareiní|Serbian Dinar|Libyan Dinar|Lebanese Pound|Syrian Pound|Jamaican Dollar|Ethiopian Birr|Kwanza|CFA Franc BEAC|CFA Franc BCEAO|Peso Convertible|Cordoba Oro|El Salvador Colon|Kuna|North Korean Won|Afgani|Lek"),
     5: L("Mvdol|WIR Euro|WIR Franc|US Dollar (Next day)|USS|Uruguay Peso en Unidades Indexadas (UI)|Unidad de Fomento|Pa’anga|Tala|Vatu|Ngultrum|Rufiyaa|Tugrik|Loti|Lilangeni|Nakfa|Dalasi|Malagasy Ariary|MRO|STD|Kina|Solomon Islands Dollar|Comorian Franc|Somoni|Turkmenistan New Manat"),
     "resto": 4},
 15: {1: L("California|Texas|Florida|Nueva York|Hawái|Alaska|Washington"),
      2: L("Arizona|Nevada|Colorado|Georgia|Illinois|Luisiana|Massachusetts|Míchigan|Nueva Jersey|Ohio|Pensilvania|Utah|Virginia|Oregón|Tennessee|Kentucky|Carolina del Norte|Carolina del Sur|Misisipi|Alabama|Kansas|Oklahoma|Nuevo México|Minnesota|Wisconsin|Indiana|Misuri"),
      4: L("Dakota del Norte|Dakota del Sur|Idaho|Nebraska|Iowa|Arkansas|Montana|Maryland|Connecticut"),
      5: L("Vermont|Delaware|Rhode Island|Nuevo Hampshire|Wyoming|Virginia Occidental|Maine"), "resto": 3},
 16: {1: L("Hidrógeno|Oxígeno|Carbono|Nitrógeno|Hierro|Oro|Plata|Cobre|Helio|Sodio|Calcio|Uranio|Plomo|Mercurio|Aluminio|Litio|Cloro|Zinc|Azufre|Potasio"),
      2: L("Magnesio|Fósforo|Silicio|Neón|Argón|Estaño|Níquel|Platino|Titanio|Cobalto|Cromo|Yodo|Flúor|Radio|Plutonio|Wolframio|Manganeso|Arsénico|Bromo|Boro"),
      3: L("Berilio|Kriptón|Xenón|Radón|Cesio|Bario|Estroncio|Cadmio|Bismuto|Paladio|Iridio|Osmio|Molibdeno|Vanadio|Galio|Germanio|Selenio|Antimonio|Telurio|Polonio|Torio|Neodimio|Rubidio|Circonio|Einsteinio|Californio|Americio|Curio|Nobelio|Fermio"),
      5: L("Oganesón|Tenesino|Livermorio|Moscovio|Nihonio|Flerovio|Copernicio|Roentgenio|Darmstadtio|Meitnerio|Hassio|Bohrio|Seaborgio|Dubnio|Rutherfordio|Protactinio|Prometio|Astato|Lawrencio|Mendelevio|Tulio|Holmio|Disprosio|Terbio|Lutecio|Iterbio|Erbio|Praseodimio"),
      "resto": 4},
 17: {1: L("Osa Mayor|Osa Menor|Orión|Casiopea|Aries|Tauro|Géminis|Cáncer|Leo|Virgo|Libra|Escorpio|Sagitario|Capricornio|Acuario|Piscis"),
      2: L("Cruz del Sur|Andrómeda|Pegaso|Perseo|Can Mayor|Dragón|Hércules|Cisne|Lira|Centauro|Hidra|Fénix|Águila|Delfín|Ofiuco"),
      3: L("Can Menor|Cefeo|Auriga (Cochero)|Boyero|Corona Boreal|Corona Austral|Cuervo|Ballena|Liebre|Lobo|Lince|Paloma|Unicornio|Flecha|Triángulo|Serpiente|Erídano|Cabellera de Berenice|Pez Austral|Vela|Popa|Carina (Quilla)|Tucán|Pavo|Grulla|Camaleón"),
      5: L("Antlia (Máquina Neumática)|Buril|Horno|Reloj|Retículo|Octante|Mesa|Microscopio|Pintor|Escultor|Sextante|Telescopio|Compás|Escuadra|Brújula|Caballito|Escudo|Indio|Ave del Paraíso|Altar|Hidra Macho|Leo Menor|Lagarto|Canes Venatici (Lebreles)|Zorra|Dorado|Pez Volador|Jirafa (Camelopardalis)|Mosca|Triángulo Austral|Cráter"),
      "resto": 4},
 18: {1: L("Pikachu|Charmander|Bulbasaur|Squirtle|Charizard|Mewtwo|Mew|Jigglypuff|Meowth|Psyduck|Snorlax|Eevee|Gengar|Magikarp|Gyarados|Raichu|Blastoise|Venusaur"),
      2: L("Pidgey|Rattata|Caterpie|Weedle|Zubat|Geodude|Onix|Ditto|Vulpix|Ninetales|Growlithe|Arcanine|Machamp|Alakazam|Abra|Slowpoke|Lapras|Dragonite|Articuno|Zapdos|Moltres|Vaporeon|Jolteon|Flareon|Cubone|Mr. Mime|Voltorb|Ekans|Butterfree|Clefairy|Koffing|Staryu|Starmie|Horsea|Ponyta|Diglett|Oddish|Bellsprout|Chansey|Hitmonlee|Hitmonchan|Scyther|Jynx|Aerodactyl|Dratini|Charmeleon|Wartortle|Ivysaur|Pidgeot|Nidoking|Nidoqueen|Haunter|Gastly|Farfetch'd|Kangaskhan"),
      4: L("Graveler|Gloom|Vileplume|Golbat|Sandslash|Primeape|Golduck|Slowbro|Magneton|Muk|Cloyster|Hypno|Exeggutor|Marowak|Seadra|Omastar|Kabutops|Dragonair|Nidorina|Nidorino|Clefable|Wigglytuff|Fearow|Raticate|Pidgeotto|Kadabra|Machoke|Tentacruel|Electrode|Persian|Poliwhirl|Poliwrath|Rhyhorn"),
      5: L("Venomoth|Venonat|Parasect|Paras|Tangela|Seaking|Dewgong|Dodrio|Doduo|Weepinbell|Kingler|Krabby|Drowzee|Exeggcute|Grimer|Shellder|Spearow|Sandshrew|Kakuna"),
      "resto": 3},
}

# ─────────────────────────── respuestas que faltaban ───────────────────────────
from nuevas import NUEVAS

# ─────────────────────────── formas de escribir ───────────────────────────
ALIAS_CAT = {
 2: {"Santa Cruz de Tenerife":"Tenerife", "Las Palmas":"Gran Canaria", "Alicante":"Alacant", "Castellón":"Castelló",
     "Valencia":"València", "Navarra":"Nafarroa", "Asturias":"Principado de Asturias"},
 3: {"Santa Cruz de Tenerife":"Santa Cruz", "Alicante":"Alacant", "Castellón de la Plana":"Castelló", "Valencia":"València"},
 1: {"Cataluña":"Catalunya", "Canarias":"Islas Canarias", "Illes Balears":"Islas Baleares"},
 4: {"Alhambra, Generalife y Albaicín de Granada":"Alhambra;Generalife;Albaicín;Alhambra de Granada",
     "Obras de Antoni Gaudí":"Sagrada Familia;Gaudí;Park Güell;Casa Batlló;Casa Milà;La Pedrera;Palau Güell",
     "Centro histórico de Córdoba":"Mezquita de Córdoba;Mezquita-Catedral de Córdoba;Mezquita",
     "Monasterio y sitio de El Escorial en Madrid":"El Escorial;Monasterio de El Escorial;San Lorenzo de El Escorial",
     "Monumentos de Oviedo y del reino de Asturias":"Prerrománico asturiano;Santa María del Naranco;San Miguel de Lillo",
     "Ciudad vieja de Ávila e iglesias extramuros":"Murallas de Ávila;Muralla de Ávila;Ávila",
     "Ciudad vieja de Santiago de Compostela":"Santiago de Compostela;Catedral de Santiago",
     "Ciudad vieja y acueducto de Segovia":"Acueducto de Segovia;Segovia",
     "Cueva de Altamira y arte rupestre paleolítico del norte de España":"Altamira;Cuevas de Altamira;Cueva de Altamira",
     "Arquitectura mudéjar de Aragón":"Mudéjar aragonés;Torres mudéjares de Teruel;Mudéjar de Teruel",
     "Ciudad vieja de Cáceres":"Cáceres", "Ciudad histórica de Toledo":"Toledo",
     "Parque Nacional de Garajonay":"Garajonay",
     "Catedral, alcázar y Archivo de Indias de Sevilla":"Catedral de Sevilla;Giralda;Real Alcázar de Sevilla;Alcázar de Sevilla;Archivo de Indias",
     "Ciudad vieja de Salamanca":"Salamanca", "Monasterio de Poblet":"Poblet",
     "Caminos de Santiago de Compostela: Camino francés y Caminos del Norte de España":"Camino de Santiago;Camino francés",
     "Conjunto arqueológico de Mérida":"Mérida;Teatro romano de Mérida;Mérida romana",
     "Real Monasterio de Santa María de Guadalupe":"Monasterio de Guadalupe;Guadalupe",
     "Parque Nacional de Doñana":"Doñana", "Lonja de la seda de Valencia":"Lonja de Valencia;La Lonja",
     "Ciudad histórica fortificada de Cuenca":"Cuenca;Casas colgadas",
     "Monasterios de San Millán de Yuso y de Suso":"San Millán de la Cogolla;Yuso y Suso",
     "Palau de la Música Catalana y hospital de Sant Pau en Barcelona":"Palau de la Música;Hospital de Sant Pau;Sant Pau",
     "Pirineos - Monte Perdido":"Monte Perdido;Ordesa",
     "Arte rupestre del arco mediterráneo de la Península Ibérica":"Arte rupestre levantino",
     "Universidad y recinto histórico de Alcalá de Henares":"Alcalá de Henares;Universidad de Alcalá",
     "Sitios de arte rupestre prehistórico del Valle del Côa y de Siega Verde":"Siega Verde",
     "Ibiza, biodiversidad y cultura":"Ibiza;Dalt Vila;Posidonia", "San Cristóbal de La Laguna":"La Laguna",
     "Iglesias románicas catalanas de Vall del Boí":"Vall de Boí;Taüll", "Muralla romana de Lugo":"Muralla de Lugo",
     "Palmeral de Elche":"Palmeral", "Conjunto arqueológico de Tarragona":"Tarraco;Tarragona",
     "Sitio arqueológico de Atapuerca":"Atapuerca", "Paisaje cultural de Aranjuez":"Aranjuez",
     "Conjuntos monumentales renacentistas de Úbeda y Baeza":"Úbeda;Baeza;Úbeda y Baeza",
     "Puente de Vizcaya":"Puente colgante;Puente Bizkaia",
     "Bosques antiguos y primarios de hayas de los Cárpatos y otras regiones de Europa":"Hayedos;Hayedo de Montejo",
     "Parque Nacional del Teide":"Teide", "El Paisaje Cultural de la Serra de Tramuntana":"Tramuntana;Sierra de Tramuntana;Serra de Tramuntana",
     "Patrimonio del mercurio (Almadén e Idria)":"Almadén;Minas de Almadén",
     "Dólmenes de Antequera":"Antequera;Dolmen de Menga", "Ciudad califal de Medina Azahara":"Medina Azahara;Madinat al-Zahra",
     "Paisaje cultural del Risco Caído y montañas sagradas de Gran Canaria":"Risco Caído",
     "Paseo del Prado y el Buen Retiro, paisaje de las artes y las ciencias":"Paseo del Prado;Retiro;Parque del Retiro;Paisaje de la Luz",
     "Menorca talayótica":"Talayots"},
 5: {"Athletic Club":"Athletic;Athletic Bilbao;Athletic de Bilbao", "Atlético de Madrid":"Atlético;Atleti",
     "CA Osasuna":"Osasuna", "Celta":"Celta de Vigo;RC Celta", "Deportivo Alavés":"Alavés", "Elche CF":"Elche",
     "FC Barcelona":"Barcelona;Barça;Barsa", "Getafe CF":"Getafe", "Levante UD":"Levante", "Málaga CF":"Málaga",
     "Racing Club de Santander":"Racing;Racing de Santander", "Rayo Vallecano":"Rayo",
     "RC Deportivo de La Coruña":"Deportivo;Dépor;Deportivo de La Coruña", "RCD Espanyol de Barcelona":"Espanyol",
     "Real Betis":"Betis", "Real Madrid":"Madrid", "Real Sociedad":"La Real", "Sevilla FC":"Sevilla",
     "Valencia CF":"Valencia", "Villarreal CF":"Villarreal"},
 7: {"Algiers":"Argel", "Yerevan":"Ereván", "Vienna":"Viena", "Baku":"Bakú", "Nassau":"Nasáu", "Dhaka":"Daca",
     "Brussels":"Bruselas", "Belmopan":"Belmopán", "Porto-Novo":"Porto Novo", "Thimphu":"Timbu", "Sucre":"La Paz",
     "Brasília":"Brasilia", "Sofia":"Sofía", "Ouagadougou":"Uagadugú", "Phnom Penh":"Nom Pen", "Yaoundé":"Yaundé",
     "N'Djamena":"Yamena", "Beijing":"Pekín;Beijing", "Havana":"La Habana;Habana", "Prague":"Praga", "Pyongyang":"Pionyang",
     "Copenhagen":"Copenhague", "Djibouti":"Yibuti", "Cairo":"El Cairo", "Tallinn":"Tallin", "Addis Ababa":"Adís Abeba",
     "Paris":"París", "Tbilisi":"Tiflis", "Berlin":"Berlín", "Accra":"Acra", "Athens":"Atenas", "St. George's":"Saint George's",
     "Guatemala City":"Ciudad de Guatemala;Guatemala", "Conakry":"Conakri", "Bissau":"Bisáu", "Port-au-Prince":"Puerto Príncipe",
     "Reykjavik":"Reikiavik", "New Delhi":"Nueva Delhi;Delhi", "Jakarta":"Yakarta", "Tehran":"Teherán", "Baghdad":"Bagdad",
     "Dublin":"Dublín", "Jerusalem":"Jerusalén", "Rome":"Roma", "Tokyo":"Tokio", "Amman":"Ammán", "Astana":"Astaná;Nursultán",
     "Kuwait City":"Kuwait;Ciudad de Kuwait", "Bishkek":"Biskek", "Vientiane":"Vientián", "Tripoli":"Trípoli",
     "Vilnius":"Vilna", "Luxembourg":"Luxemburgo", "Lilongwe":"Lilongüe", "Valletta":"La Valeta;Valeta",
     "Nouakchott":"Nuakchot", "Port Louis":"Port-Louis", "Mexico City":"Ciudad de México;México DF;CDMX",
     "Monaco":"Mónaco", "Ulan Bator":"Ulán Bator", "Kathmandu":"Katmandú", "Amsterdam":"Ámsterdam", "Abuja":"Abuya",
     "Skopje":"Skopie", "Muscat":"Mascate", "Panama City":"Ciudad de Panamá;Panamá", "Warsaw":"Varsovia",
     "Lisbon":"Lisboa", "Seoul":"Seúl", "Chișinău":"Chisináu;Chisinau", "Bucharest":"Bucarest", "Moscow":"Moscú",
     "City of San Marino":"San Marino", "São Tomé":"Santo Tomé", "Riyadh":"Riad", "Belgrade":"Belgrado",
     "Singapore":"Singapur", "Ljubljana":"Liubliana", "Mogadishu":"Mogadiscio", "Pretoria":"Ciudad del Cabo;Bloemfontein",
     "Juba":"Yuba", "Sri Jayawardenepura Kotte":"Colombo;Kotte", "Khartoum":"Jartum", "Stockholm":"Estocolmo",
     "Bern":"Berna", "Damascus":"Damasco", "Dushanbe":"Dusambé", "Nuku'alofa":"Nukualofa", "Port of Spain":"Puerto España",
     "Tunis":"Túnez", "Ashgabat":"Asjabad", "Kiev":"Kyiv;Kíiv", "Abu Dhabi":"Abu Dabi", "Washington D.C.":"Washington",
     "Tashkent":"Taskent", "Hanoi":"Hanói", "Sana'a":"Saná", "Andorra la Vella":"Andorra la Vieja", "Naipyidó":"Naypyidaw",
     "Londres":"London", "Kingstown":"Kingstown", "Yamoussoukro":"Yamusukro", "Malé":"Male", "Asunción":"Asuncion",
     "Kinshasa":"Kinsasa", "Maputo":"Maputo", "Nicosia":"Nicosia", "Minsk":"Minsk", "Bandar Seri Begawan":"Bandar Seri Begawan"},
 8: {"Dólar estadounidense":"Dólar;Dólares;Dólar americano;USD", "Euro":"Euros", "Yen japonés":"Yen", "Yuan chino":"Yuan;Renminbi",
     "Won surcoreano":"Won", "Rublo ruso":"Rublo", "Lira turca":"Lira", "Real brasileño":"Real", "Rupia india":"Rupia",
     "Franco suizo":"Franco", "Peso mexicano":"Peso", "Corona sueca":"Corona", "Riyal saudí":"Riyal", "Rial iraní":"Rial",
     "Dírham marroquí":"Dírham;Dirham", "Chelín keniano":"Chelín", "Sol peruano":"Sol", "Bolívar venezolano":"Bolívar;Bolívar soberano;VES",
     "Zloty polaco":"Zloty", "Forinto húngaro":"Forint;Forinto", "Nuevo séquel israelí":"Shekel;Séquel", "Dinar argelino":"Dinar",
     "Azerbaijan Manat":"Manat azerbaiyano;Manat", "Convertible Mark":"Marco convertible", "Barbados Dollar":"Dólar de Barbados",
     "Burundi Franc":"Franco de Burundi", "Brunei Dollar":"Dólar de Brunéi", "Bahamian Dollar":"Dólar bahameño",
     "BYR":"Rublo bielorruso;BYN", "Belize Dollar":"Dólar beliceño", "Congolese Franc":"Franco congoleño",
     "Costa Rican Colon":"Colón costarricense;Colón", "Cuban Peso":"Peso cubano", "Peso Convertible":"Peso cubano convertible",
     "Cabo Verde Escudo":"Escudo caboverdiano;Escudo", "Djibouti Franc":"Franco yibutiano", "Dominican Peso":"Peso dominicano",
     "Ethiopian Birr":"Birr etíope;Birr", "Fiji Dollar":"Dólar fiyiano", "Guinean Franc":"Franco guineano",
     "Guyana Dollar":"Dólar guyanés", "Jamaican Dollar":"Dólar jamaicano", "Comorian Franc":"Franco comorense",
     "North Korean Won":"Won norcoreano", "Lao Kip":"Kip laosiano;Kip", "Lebanese Pound":"Libra libanesa",
     "Liberian Dollar":"Dólar liberiano", "Libyan Dinar":"Dinar libio", "Moldovan Leu":"Leu moldavo",
     "Malagasy Ariary":"Ariary malgache;Ariary", "MRO":"Uguiya;Ouguiya;MRU", "Mauritius Rupee":"Rupia de Mauricio",
     "Malawi Kwacha":"Kwacha malauí", "Mozambique Metical":"Metical", "Namibia Dollar":"Dólar namibio",
     "Cordoba Oro":"Córdoba nicaragüense;Córdoba", "Rwanda Franc":"Franco ruandés",
     "Solomon Islands Dollar":"Dólar de las Islas Salomón", "Seychelles Rupee":"Rupia de Seychelles",
     "Sudanese Pound":"Libra sudanesa", "Somali Shilling":"Chelín somalí", "Surinam Dollar":"Dólar surinamés",
     "South Sudanese Pound":"Libra sursudanesa", "STD":"Dobra;STN", "El Salvador Colon":"Colón salvadoreño",
     "Syrian Pound":"Libra siria", "Turkmenistan New Manat":"Manat turcomano", "Trinidad and Tobago Dollar":"Dólar de Trinidad y Tobago",
     "Tanzanian Shilling":"Chelín tanzano", "Uganda Shilling":"Chelín ugandés", "Uzbekistan Sum":"Som uzbeko",
     "CFA Franc BEAC":"Franco CFA", "CFA Franc BCEAO":"Franco CFA de África Occidental", "East Caribbean Dollar":"Dólar del Caribe Oriental",
     "Yemeni Rial":"Rial yemení", "Serbian Dinar":"Dinar serbio", "ZMK":"Kwacha zambiano;Kwacha;ZMW", "Rand":"Rand sudafricano",
     "Tala":"Tala samoano", "Leone":"Leona;SLE", "Denar":"Denar macedonio", "Taka bangladesí":"Taka", "Lev búlgaro":"Lev",
     "Leu rumano":"Leu", "Grivna ucraniana":"Grivna", "Baht tailandés":"Baht", "Dong vietnamita":"Dong", "Ringit malasio":"Ringgit",
     "Naira nigeriana":"Naira", "Cedi ghanés":"Cedi", "Guaraní paraguayo":"Guaraní", "Libra egipcia":"Libra egipcia"},
 15: {"Hawái":"Hawaii", "Míchigan":"Michigan", "Misisipi":"Mississippi", "Misuri":"Missouri", "Luisiana":"Louisiana",
      "Nueva York":"New York", "Nueva Jersey":"New Jersey", "Nuevo México":"New Mexico", "Nuevo Hampshire":"New Hampshire",
      "Carolina del Norte":"North Carolina", "Carolina del Sur":"South Carolina", "Dakota del Norte":"North Dakota",
      "Dakota del Sur":"South Dakota", "Pensilvania":"Pennsylvania", "Oregón":"Oregon", "Virginia Occidental":"West Virginia"},
 16: {"Wolframio":"Tungsteno", "Tantalio":"Tántalo", "Zinc":"Cinc", "Kriptón":"Criptón", "Astato":"Astatino",
      "Tenesino":"Teneso", "Lawrencio":"Laurencio", "Circonio":"Zirconio", "Yodo":"Iodo", "Einsteinio":"Einstenio",
      "Darmstadtio":"Darmstadio", "Oganesón":"Oganesson", "Rutherfordio":"Rutherfordium"},
 17: {"Escorpio":"Escorpión;Scorpius", "Osa Mayor":"Ursa Major;El Carro", "Osa Menor":"Ursa Minor", "Orión":"Orion",
      "Cisne":"Cygnus", "Lira":"Lyra", "Águila":"Aquila", "Casiopea":"Cassiopeia", "Can Mayor":"Canis Major;Perro Mayor",
      "Can Menor":"Canis Minor;Perro Menor", "Centauro":"Centaurus", "Dragón":"Draco", "Pegaso":"Pegasus", "Perseo":"Perseus",
      "Tauro":"Taurus", "Géminis":"Gemini", "Sagitario":"Sagittarius", "Capricornio":"Capricornus", "Acuario":"Aquarius",
      "Cruz del Sur":"Crux", "Hidra":"Hydra", "Ofiuco":"Ophiuchus;Serpentario", "Andrómeda":"Andromeda", "Cefeo":"Cepheus",
      "Boyero":"Bootes", "Hércules":"Hercules", "Fénix":"Phoenix", "Vela":"Velas", "Popa":"Puppis", "Ballena":"Cetus",
      "Zorra":"Vulpecula", "Unicornio":"Monoceros", "Lobo":"Lupus", "Liebre":"Lepus"},
 30: {"Kimi Räikkönen":"Raikkonen", "Mika Häkkinen":"Hakkinen"},
 38: {"Beast":"Bestia", "Captain Hook":"Capitán Garfio;Garfio", "Tinker Bell":"Campanilla", "Eeyore":"Igor",
      "Scrooge McDuck":"Tío Gilito", "Huey":"Juanito", "Dewey":"Jorgito", "Louie":"Jaimito", "Jiminy Cricket":"Pepito Grillo",
      "Maleficent":"Maléfica", "Hercules":"Hércules", "Aladdin":"Aladdín", "Jasmine":"Jasmín", "Belle":"Bella",
      "Lady":"Reina", "Tramp":"Golfo", "Chip":"Chip", "Dale":"Chop", "Daisy Duck":"Pata Daisy;Daisy", "Pete":"Pedro",
      "Ursula":"Úrsula", "Merida":"Mérida", "Mulan":"Mulán", "Tarzan":"Tarzán", "Oswald the Lucky Rabbit":"Oswald",
      "Mickey Mouse":"Mickey", "Winnie the Pooh":"Winnie;Pooh", "Snow White":"Blancanieves", "Cinderella":"Cenicienta",
      "Moana":"Vaiana", "Madame Mim":"Mim"},
 39: {"Lightning McQueen":"Rayo McQueen;McQueen", "Mater":"Mate", "Sulley":"Sully", "Mr. Potato Head":"Señor Patata",
      "Joy":"Alegría", "Sadness":"Tristeza", "Anger":"Ira", "Fear":"Miedo", "Disgust":"Asco", "EVE":"Eva",
      "Mr. Incredible":"Señor Increíble", "Violet Parr":"Violeta", "Frozone":"Frozono", "Slinky Dog":"Slinky",
      "Bo Peep":"Betty", "Merida":"Mérida", "Edna Mode":"Edna Moda;Edna", "Elastigirl":"Helen Parr;Helen",
      "Carl Fredricksen":"Carl", "Miguel Rivera":"Miguel", "Buzz Lightyear":"Buzz", "Mike Wazowski":"Mike", "Randall Boggs":"Randall"},
 40: {"Spider-Man":"Hombre Araña", "Captain America":"Capitán América", "Black Widow":"Viuda Negra", "Winter Soldier":"Soldado de Invierno",
      "Falcon":"Halcón", "Vision":"Visión", "Punisher":"Castigador", "Professor X":"Profesor X;Charles Xavier",
      "Cyclops":"Cíclope", "Storm":"Tormenta", "Jean Grey":"Fénix", "Rocket Raccoon":"Rocket", "Mystique":"Mística",
      "Sabretooth":"Dientes de Sable", "Beast":"Bestia", "Iceman":"Hombre de Hielo", "Colossus":"Coloso",
      "Nightcrawler":"Rondador Nocturno", "Rogue":"Pícara", "Wasp":"Avispa", "War Machine":"Máquina de Guerra",
      "Doctor Octopus":"Doc Ock", "Red Skull":"Cráneo Rojo", "Moon Knight":"Caballero Luna", "Captain Marvel":"Capitana Marvel",
      "Scarlet Witch":"Bruja Escarlata;Wanda", "Green Goblin":"Duende Verde", "Wolverine":"Lobezno", "Deadpool":"Masacre",
      "She-Hulk":"Hulka", "Ms. Marvel":"Kamala Khan", "Mole Man":"Hombre Topo", "Baron Zemo":"Zemo", "Nick Fury":"Nick Furia"},
 43: {"Wednesday":"Miércoles", "Squid Game":"El juego del calamar", "The Queen's Gambit":"Gambito de dama",
      "The Haunting of Hill House":"La maldición de Hill House", "The Haunting of Bly Manor":"La maldición de Bly Manor",
      "Bridgerton":"Los Bridgerton", "La casa de papel":"Money Heist", "Sex Education":"Sex Ed", "3 Body Problem":"El problema de los 3 cuerpos",
      "The Umbrella Academy":"Umbrella Academy", "All of Us Are Dead":"Estamos muertos", "Alice in Borderland":"Alice in Borderland",
      "Midnight Mass":"Misa de medianoche", "The Lincoln Lawyer":"El abogado del Lincoln", "Baby Reindeer":"Mi reno de peluche",
      "Dead to Me":"Muerta para mí", "Unbelievable":"Creedme", "The Diplomat":"La diplomática", "Russian Doll":"Muñeca rusa",
      "Love, Death & Robots":"Love Death and Robots"},
 44: {"The Lord of the Rings: The Rings of Power":"Los anillos de poder;El Señor de los Anillos", "Invincible":"Invencible",
      "The Marvelous Mrs. Maisel":"La maravillosa señora Maisel", "The Summer I Turned Pretty":"El verano en que me enamoré",
      "The Man in the High Castle":"El hombre en el castillo", "Good Omens":"Buenos presagios", "The Wheel of Time":"La rueda del tiempo"},
 45: {"The Simpsons":"Los Simpson", "The Fresh Prince of Bel-Air":"El príncipe de Bel-Air", "Two and a Half Men":"Dos hombres y medio",
      "How I Met Your Mother":"Cómo conocí a vuestra madre", "Everybody Loves Raymond":"Todo el mundo quiere a Raymond",
      "Malcolm in the Middle":"Malcolm", "That '70s Show":"Aquellos maravillosos 70", "It's Always Sunny in Philadelphia":"Colgados en Filadelfia",
      "Arrested Development":"Arrested Development", "The Big Bang Theory":"Big Bang", "Brooklyn Nine-Nine":"Brooklyn 99",
      "My Name Is Earl":"Me llamo Earl", "Everybody Hates Chris":"Todo el mundo odia a Chris", "3rd Rock from the Sun":"Cosas de marcianos",
      "Spin City":"Spin City", "The Middle":"The Middle", "Ghosts":"Ghosts", "Superstore":"Superstore", "The Good Place":"The Good Place",
      "Schitt's Creek":"Schitts Creek", "Curb Your Enthusiasm":"Larry David", "Derry Girls":"Derry Girls"},
 47: {"¡Rompe Ralph!":"Rompe Ralph", "Lilo & Stitch":"Lilo y Stitch", "Zootrópolis":"Zootopia", "Enredados":"Rapunzel",
      "Moana":"Vaiana", "Blancanieves y los siete enanitos":"Blancanieves", "Atlantis: El imperio perdido":"Atlantis",
      "101 dálmatas":"Los 101 dálmatas;101 dalmatas", "Las locuras del emperador":"El emperador y sus locuras"},
 48: {"The Avengers":"Los Vengadores;Vengadores", "Avengers: Endgame":"Vengadores: Endgame", "Avengers: Infinity War":"Vengadores: Infinity War",
      "Guardians of the Galaxy":"Guardianes de la Galaxia", "Captain America":"Capitán América", "Captain Marvel":"Capitana Marvel",
      "Black Panther":"Pantera Negra", "Black Widow":"Viuda Negra", "Fantastic Four":"Los 4 Fantásticos;Los Cuatro Fantásticos",
      "Eternals":"Eternos", "Avengers: Age of Ultron":"La era de Ultrón", "Spider-Man: Far From Home":"Lejos de casa",
      "Spider-Man: No Way Home":"Sin camino a casa", "Deadpool & Wolverine":"Deadpool y Lobezno", "Logan":"Lobezno"},
 58: {"Buckingham Palace":"Palacio de Buckingham", "Petronas Towers":"Torres Petronas", "Casa Blanca":"White House",
      "Casa Milà":"La Pedrera", "Louvre":"Museo del Louvre", "Coliseo":"Coliseo romano", "Ópera de Sídney":"Ópera de Sydney",
      "Guggenheim Bilbao":"Guggenheim", "Shard":"The Shard", "Fallingwater":"Casa de la Cascada"},
 60: {"Moái":"Moáis", "Terracota de Xi'an":"Guerreros de terracota", "Acrópolis de Atenas":"Acrópolis", "Torre de Pisa":"Torre inclinada de Pisa",
      "Santa Sofía":"Hagia Sophia", "Muro de las Lamentaciones":"Muro Occidental", "Chichén Itzá":"Chichen Itza"},
 73: {"COVID-19":"Covid;Coronavirus", "VIH/sida":"Sida;VIH", "Parotiditis":"Paperas", "Tosferina":"Tos ferina",
      "Resfriado común":"Resfriado;Catarro", "Rubeola":"Rubéola", "Poliomielitis":"Polio", "Mononucleosis infecciosa":"Mononucleosis",
      "Peste bubónica":"Peste", "Enfermedad de Lyme":"Lyme", "Gastroenteritis":"Gastro"},
}

# Más formas de escribir: nombres civiles de superhéroes, títulos en español, etc.
_MAS = {
 22: {"Argentina":"República Argentina"},
 25: {"Bonilla a la Vista":"Bonilla"},
 29: {"Acqua Panna":"Panna"},
 37: {"Bowser":"Rey Koopa", "Peach":"Princesa Peach", "Daisy":"Princesa Daisy", "Rosalina":"Estela",
      "Toad":"Honguito", "Piranha Plant":"Planta Piraña", "Chain Chomp":"Chomp Cadenas", "Dry Bones":"Huesitos"},
 40: {"Iron Man":"Tony Stark;Hombre de Hierro", "Captain America":"Steve Rogers", "Spider-Man":"Peter Parker",
      "Hulk":"Bruce Banner", "Black Widow":"Natasha Romanoff;Natasha", "Hawkeye":"Clint Barton;Ojo de Halcón",
      "Captain Marvel":"Carol Danvers", "Black Panther":"T'Challa;Pantera Negra", "Doctor Strange":"Stephen Strange;Doctor Extraño",
      "Ant-Man":"Scott Lang;Hombre Hormiga", "Falcon":"Sam Wilson", "Winter Soldier":"Bucky;Bucky Barnes"},
 43: {"Ginny & Georgia":"Ginny y Georgia", "Wednesday":"Wednesday Addams"},
 46: {"Casa en flames":"Casa en llamas", "Ocho apellidos vascos":"Ocho apellidos"},
 47: {"Wish":"Wish: El poder de los deseos"},
 48: {"Captain America: The First Avenger":"Capitán América: El primer vengador;El primer vengador",
      "Captain America: The Winter Soldier":"Capitán América: El soldado de invierno;El soldado de invierno",
      "Captain America: Civil War":"Capitán América: Civil War;Civil War", "Guardians of the Galaxy Vol. 2":"Guardianes de la Galaxia Vol. 2",
      "Guardians of the Galaxy Vol. 3":"Guardianes de la Galaxia Vol. 3", "Thor: The Dark World":"Thor: Un mundo oscuro",
      "Thor: Love and Thunder":"Thor: Amor y trueno", "Ant-Man and the Wasp":"Ant-Man y la Avispa",
      "Doctor Strange in the Multiverse of Madness":"Doctor Strange en el multiverso de la locura",
      "Black Panther: Wakanda Forever":"Wakanda Forever", "Spider-Man: Homecoming":"Homecoming",
      "X-Men: The Last Stand":"X-Men: La decisión final", "X-Men: First Class":"X-Men: Primera generación",
      "X-Men: Days of Future Past":"X-Men: Días del futuro pasado", "Dark Phoenix":"X-Men: Fénix Oscura",
      "Kraven the Hunter":"Kraven el cazador", "Venom: Let There Be Carnage":"Venom: Habrá matanza"},
 49: {"Jurassic Park":"Parque Jurásico"},
 50: {"J. A. Bayona":"Juan Antonio Bayona;Bayona"},
}
# Países: nombres con los que se conocen en España (valen en todas las preguntas de países)
_PAISES = {"Países Bajos":"Holanda", "República Checa":"Chequia", "República Eslovaca":"Eslovaquia",
  "República de Sudáfrica":"Sudáfrica", "Macedonia":"Macedonia del Norte", "Suazilandia":"Esuatini",
  "Congo":"República del Congo;Congo-Brazzaville", "Congo (Rep. Dem.)":"República Democrática del Congo;RD Congo;Congo-Kinshasa;Zaire",
  "Estados Unidos":"EEUU;EE UU;USA;Estados Unidos de América", "Reino Unido":"Gran Bretaña;UK",
  "Emiratos Árabes Unidos":"Emiratos;EAU", "Arabia Saudí":"Arabia Saudita", "Kirguizistán":"Kirguistán",
  "Kazajistán":"Kazajstán", "Timor Oriental":"Timor Leste", "Bielorrusia":"Belarús", "Botswana":"Botsuana",
  "Lesotho":"Lesoto", "Malawi":"Malaui", "Sierra Leone":"Sierra Leona", "Grenada":"Granada",
  "San Vicente y Granadinas":"San Vicente y las Granadinas", "Mauricio":"Isla Mauricio",
  "Guinea-Bisáu":"Guinea Bissau", "Micronesia":"Estados Federados de Micronesia", "Corea del Sur":"República de Corea",
  "Bahrein":"Baréin", "Moldavia":"Moldova", "Myanmar (Birmania)":"Myanmar;Birmania", "Rumania":"Rumanía",
  "Irán":"Iran", "Iran":"Irán", "Haiti":"Haití", "Fiyi":"Fiji", "Turquía":"Türkiye"}
for _c in (6, 9, 10, 11, 12, 13, 14):
    _MAS.setdefault(_c, {}).update(_PAISES)

for _c, _d in _MAS.items():
    for _k, _v in _d.items():
        previo = ALIAS_CAT.setdefault(_c, {}).get(_k, "")
        ALIAS_CAT[_c][_k] = ";".join(x for x in (previo, _v) if x)
